### ISSUE TITLE
Send and receive binary data

### ISSUE THREAD

**Issue by williamesp2015** [ThomasBarth/WebSockets-on-the-ESP32#1]
Thank you for having your websocket program on Github. Nowday, there is no websocket source compatible with ESP32. I am wondering if you can modify your source for binary packets like https://github.com/Links2004/arduinoWebSockets. Thank you

**Comment by ThomasBarth** [comment]
Hello William.
This is not really in issue and the wrong place to discuss it. Please use 
https://www.esp32.com/viewtopic.php?f=17&t=977
or
http://www.barth-dev.de/websockets-on-the-esp32/

Unfortunately  I very likely will have no time to port it to your project in the close future. Maybe you can do it. Give it a try ! ;)

Regards
Thomas
