### ISSUE TITLE
Hi, Websocket Client

### ISSUE THREAD

**Issue by ArminKardan** [ThomasBarth/WebSockets-on-the-ESP32#4]
Hello, Can you suggest how to turn ESP32 to Websocket Client?
Can you do it? 
Please contact me by Email or Whatsapp: +989178207012
armin.fire [at] gmail [dot] com
thank you.

**Comment by janoist1** [comment]
I'm also interested in this.

**Comment by ThomasBarth** [comment]
Hi.
No, I don't know a good WebSocket Client for the ESP32.
